notifications:
  email:
    - garcia.rodriguez.william@gmail.com

language: php

php:
  - 5.4
  - 5.5
  - 5.6

cache:
  directories:
    - vendor
    - node_modules

git:
  submodules: false

before_script:
  - composer install --no-interaction --prefer-source
  - API_ENV=dev php -S localhost:4000 web/index.php &

script: php vendor/atoum/atoum/bin/atoum && ./bin/behat tests/functional/features
